# -*- coding: utf-8 -*-
"""analise_exploratoria_titanic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KlebdzB86Si-AWXQC72tQyEgKNQ_xjqU
"""

## Etapa 1: Importação e Compreensão de Dados - INÍCIO

import pandas as pd #Importando pandas para manipulação, limpeza e análise de dados.

import matplotlib.pyplot as plt #Criar e personalizar gráficos de forma rápida e intuitiva

import seaborn as sns #Utilizada para criar gráficos atraentes, informativos e complexos com menos linhas de código

import matplotlib.ticker as mtick #formatador de eixos

try:
    url = 'https://raw.githubusercontent.com/LFelipeMartins-stack/analise_exploratoria_titanic/main/dados/titanic_dataset.csv'
    df = pd.read_csv(url)
    print("Dados carregados via GitHub com sucesso!\n")
except:
    # Fallback caso o link falhe: lê o arquivo local
    df = pd.read_csv('/content/titanic_dataset.csv')
    print("Dados carregados localmente.\n")

df.head() #Visualizando as cinco primeiras linhas do Dataframe de forma limpa no google_colab

df.info() #Visualizando resumo técnico e conciso de um DataFrame de forma limpa no google_colab

df.describe() #Visualizando estatísticas descritivas resumidas de um DataFrame de forma limpa no google_colab

## Etapa 1: Importação e Compreensão de Dados - FIM

## Etapa 2: Limpeza e Tratamento de Dados - INÍCIO

duplicateRows = df[df.duplicated()] #Criando variável para identificar valores duplicados no dataset

print("Valores duplicados ANTES do tratamento:")
print(len(duplicateRows))

print("Valores nulos ANTES do tratamento:")
display(df.isnull().sum())

mediana_idade = df['Age'].median()
df['Age'] = df['Age'].fillna(mediana_idade) #Para a idade resolvi calcular a mediana e preencher os valores vazios com ela. Mediana usada ao invés de média pois não sofre influência de idades extremas

df = df.drop(columns=['Cabin']) #Como faltam quase 80% dos dados da Cabine, ela se torna inútil para analise. Removida!

df = df.dropna(subset=['Embarked']) #Como faltam apenas 2 valores nessa coluna, removi as duas que estavam nulos.

remove_columns = ['PassengerId', 'Name', 'Ticket']
df = df.drop(columns=remove_columns) #PassengerId, Name e Ticket não têm relação causal com a sobrevivência da pessoa, então removi porque entendo que são desnecessários para analise de dados atual.

df['Sex'] = df['Sex'].astype('category')
df['Embarked'] = df['Embarked'].astype('category') #Transformação de tipo texto e número em categorias para economizar memória RAM e acelerar processo na hora de gerar gráficos Seaborn/Matplotlib.

df['Pclass'] = df['Pclass'].astype('category') #Transformando o Pclass como categoria também, primeira classe, segunda classe, evitando possiveis conflitos.

print("\nValores nulos DEPOIS do tratamento:")
display(df.isnull().sum())

## Etapa 2: Limpeza e Tratamento de Dados - FIM

## Etapa 3: Análises e Agrupamentos - INÍCIO

overall_survival_rate = df['Survived'].mean() * 100 #Percentual geral de sobrevivente

print(f"-> Taxa de sobrevivência GERAL do navio: {overall_survival_rate:.2f}%")

survival_sex = df.groupby('Sex', observed=True)['Survived'].mean().reset_index() # Agrupamento por Sexo

survival_sex['Survived'] = (survival_sex['Survived'] * 100).round(2).astype(str) + '%'# Agrupamento por Sexo

survival_sex.columns = ['Gênero', 'Taxa de Sobrevivência']# Agrupamento por Sexo

survival_class = df.groupby('Pclass', observed=True)['Survived'].mean().reset_index() # Agrupamento por Classe

survival_class['Survived'] = (survival_class['Survived'] * 100).round(2).astype(str) + '%' # Agrupamento por Classe

survival_class.columns = ['Classe do Bilhete', 'Taxa de Sobrevivência'] # Agrupamento por Classe

cortes = [0, 17, 59, 100] #Separação de grupos por faixa etária

track_names = ['Menores (0-17)', 'Adultos (18-59)', 'Idosos (60+)'] # Agrupamento por Faixa Etária

df['Faixa_Etaria'] = pd.cut(df['Age'], bins=cortes, labels=track_names) # Agrupamento por Faixa Etária

survival_age = df.groupby('Faixa_Etaria', observed=True)['Survived'].mean().reset_index() # Agrupamento por Faixa Etária

survival_age['Survived'] = (survival_age['Survived'] * 100).round(2).astype(str) + '%' # Agrupamento por Faixa Etária

survival_age.columns = ['Faixa Etária', 'Taxa de Sobrevivência'] # Agrupamento por Faixa Etária

print("--- ANÁLISE POR GÊNERO ---")
display(survival_sex)

print("\n--- ANÁLISE POR CLASSE SOCIAL ---")
display(survival_class)

print("\n--- ANÁLISE POR FAIXA ETÁRIA ---")
display(survival_age)

## Etapa 3: Análises e Agrupamentos - FIM

## Etapa 4: Visualização de Dados Graficamente - INÍCIO

sns.set_theme(style="whitegrid", palette="muted") # Estilo e paleta definidos

# GRÁFICO 1: Distribuição da Idade (Histograma)
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='Age', bins=30, kde=True, color='steelblue')
plt.title('Distribuição Etária dos Passageiros do Titanic', fontsize=16, fontweight='bold', pad=15)
plt.xlabel('Idade (anos)', fontsize=12)
plt.ylabel('Frequência (Quantidade de Passageiros)', fontsize=12)
plt.show()

# GRÁFICO 2: Relação entre Sexo e Sobrevivência (Gráfico de Barras)
plt.figure(figsize=(10, 6))
ax = sns.barplot(
    data=df,
    x='Sex',
    y='Survived',
    hue='Sex',
    legend=False,
    order=['male', 'female'],
    palette=['#3498db', '#e74c3c'])
plt.title('Taxa de Sobrevivência por Gênero', fontsize=16, fontweight='bold', pad=15)
plt.xlabel('Gênero', fontsize=12)
plt.ylabel('Taxa de Sobrevivência', fontsize=12)
ax.set_xticks([0, 1])
ax.set_xticklabels(['Masculino', 'Feminino'])
ax.yaxis.set_major_formatter(mtick.PercentFormatter(1.0)) #Transformando o eixe em porcentagem
plt.show()

## Etapa 4: Visualização de Dados Graficamente - FIM